# coding: utf-8

"""
    Pure1 Public REST API

    Pure1 Public REST API, developed by [Pure Storage, Inc.](https://www.purestorage.com) The Pure1 REST API 2.0 offers one single form of authentication: OAuth 2.0 via the [Token Exchange protocol](https://datatracker.ietf.org/doc/draft-ietf-oauth-token-exchange). OAuth 2.0 is an open protocol to allow secure authorization in a simple and standard method from web, mobile, desktop and background applications. Note that the [Authentication](#section/Authentication) section below mentions 'API Key' as the security scheme type. This is solely for the purpose of allowing testing this API with [Swagger UI](https://static.pure1.purestorage.com/api-swagger/index.html). [Knowledge base reference documentation](https://support.purestorage.com/Pure1/Pure1_Manage/Pure1_Manage_-_REST_API/Pure1_Manage_-_REST_API__Reference)

    The version of the OpenAPI document: 1.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from pypureclient.pure1.Pure1_1_3.models.drive_array_status import DriveArrayStatus
from typing import Optional, Set
from typing_extensions import Self

class Drive(BaseModel):
    """
    Drive
    """ # noqa: E501
    as_of: Optional[StrictInt] = Field(default=None, description="The freshness of the data (timestamp in millis since epoch).", alias="_as_of")
    id: Optional[StrictStr] = Field(default=None, description="A non-modifiable, globally unique ID chosen by the system.")
    name: Optional[StrictStr] = Field(default=None, description="A non-modifiable, locally unique name chosen by the system.")
    arrays: Optional[Annotated[List[DriveArrayStatus], Field(min_length=1)]] = Field(default=None, description="A list of arrays that contain this drive. Each drive should only exist on one array.")
    capacity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Physical storage capacity of the module (in bytes).")
    details: Optional[StrictStr] = Field(default=None, description="Details about the status of the module if status is not `healthy`.")
    protocol: Optional[StrictStr] = Field(default=None, description="Storage protocol of the module. Values include `NVMe` and `SAS`.")
    status: Optional[StrictStr] = Field(default=None, description="Current status of the module. Values include `empty`, `failed`, `healthy`, `identifying`, `missing`, `recovering`, `unadmitted`, `unhealthy`, `unrecognized`, and `updating`.")
    type: Optional[StrictStr] = Field(default=None, description="The type of the module. Values include `cache`, `NVRAM`, `SSD`, and `virtual`.")
    __properties: ClassVar[List[str]] = ["_as_of", "id", "name", "arrays", "capacity", "details", "protocol", "status", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    def to_dict(self, include_readonly: bool = False) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.

        * OpenAPI `readOnly` fields are excluded, if `include_readonly` is `False`.
        """
        excluded_fields: Set[str] = set([
            "as_of",
            "id",
            "name",
            "capacity",
            "details",
            "protocol",
            "status",
            "type",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=set() if include_readonly else excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in arrays (list)
        if self.arrays and (include_readonly or "arrays" not in excluded_fields):
            _items = []
            for _item_arrays in self.arrays:
                if _item_arrays:
                    _items.append(_item_arrays.to_dict())
            _dict['arrays'] = _items
        return _dict

    def __getitem__(self, key):
        return getattr(self, key)

    def __setitem__(self, key, value):
        setattr(self, key, value)

    def __delitem__(self, key):
        setattr(self, key, None)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Drive from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Drive from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_construct(_fields_set=None, **{
            "as_of": obj.get("_as_of"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "arrays": [DriveArrayStatus.from_dict(_item) for _item in obj["arrays"]] if obj.get("arrays") is not None else None,
            "capacity": obj.get("capacity"),
            "details": obj.get("details"),
            "protocol": obj.get("protocol"),
            "status": obj.get("status"),
            "type": obj.get("type")
        })
        return _obj


