# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('.'))
if os.getenv('BUILDDIR'):
    sys.path.insert(0, os.path.abspath(os.getenv('BUILDDIR')))
os.environ['DOCS_GENERATION'] = 'true'


# -- Project information -----------------------------------------------------

project = u'py-pure-client'
copyright = u'2023, Pure Storage, Inc.'
author = u'Pure Storage, Inc.'

# The short X.Y version
version = u'1.66'
# The full version, including alpha/beta/rc tags
release = u'1.66.0'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    u'_build',
    'Thumbs.db',
    '.DS_Store',
    # be careful if you want to modify list below,
    # without those exclusions readthedocs will die due to OOM
    # FlashArray
    'source/*.FA_2_0.*',
    'source/*.FA_2_1.*',
    'source/*.FA_2_2.*',
    'source/*.FA_2_3.*',
    'source/*.FA_2_4.*',
    'source/*.FA_2_5.*',
    'source/*.FA_2_6.*',
    'source/*.FA_2_7.*',
    'source/*.FA_2_8.*',
    'source/*.FA_2_9.*',
    'source/*.FA_2_10.*',
    'source/*.FA_2_11.*',
    'source/*.FA_2_12.*',
    'source/*.FA_2_13.*',
    'source/*.FA_2_14.*',
    'source/*.FA_2_15.*',
    'source/*.FA_2_16.*',
    'source/*.FA_2_17.*',
    'source/*.FA_2_18.*',
    'source/*.FA_2_19.*',
    'source/*.FA_2_20.*',
    'source/*.FA_2_21.*',
    'source/*.FA_2_22.*',
    'source/*.FA_2_23.*',
    'source/*.FA_2_24.*',
    'source/*.FA_2_25.*',
    'source/*.FA_2_26.*',
    'source/*.FA_2_27.*',
    'source/*.FA_2_28.*',
    'source/*.FA_2_29.*',
    'source/*.FA_2_30.*',
    'source/*.FA_2_31.*',
    'source/*.FA_2_32.*',
    #    'source/*.FA_2_33.*',
    #    'source/*.FA_2_34.*',
    # FlashBlade
    'source/*.FB_2_0.*',
    'source/*.FB_2_1.*',
    'source/*.FB_2_2.*',
    'source/*.FB_2_3.*',
    'source/*.FB_2_4.*',
    'source/*.FB_2_5.*',
    'source/*.FB_2_6.*',
    'source/*.FB_2_7.*',
    #    'source/*.FB_2_8.*',
    'source/*.FB_2_9.*',
    'source/*.FB_2_10.*',
    'source/*.FB_2_11.*',
    'source/*.FB_2_12.*',
    #   'source/*.FB_2_13.*',
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'py-pure-clientdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'py-pure-client.tex', u'py-pure-client Documentation',
     u'Pure Storage', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'py-pure-client', u'py-pure-client Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'py-pure-client', u'py-pure-client Documentation',
     author, 'py-pure-client', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------
napoleon_include_init_with_doc = True
napoleon_include_special_with_doc = True
